version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
    groups:
      dotnet:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /src/frontend
    schedule:
      interval: weekly
    target-branch: staging
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
